# Generated by Django 4.1.6 on 2023-03-31 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_image_imagepost_image1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImagePost',
        ),
    ]
