# Generated by Django 4.1.6 on 2023-03-31 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_image2_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image3',
            field=models.ImageField(default='', upload_to='blog/images/post'),
        ),
        migrations.AddField(
            model_name='post',
            name='image4',
            field=models.ImageField(default='', upload_to='blog/images/post'),
        ),
    ]
